### PR TITLE
chore: better notice

### PR DESCRIPTION
**Pull request by shaoshuai0102**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by gxcsoccer** [comment]
ci 过了，你来发布吧 @shaoshuai0102

**Comment by shaoshuai0102** [comment]
ok

**Comment by shaoshuai0102** [comment]
@gxcsoccer 给我加个权限

**Comment by gxcsoccer** [comment]
\+ shaoshuai0102 (cluster-client)

done

**Comment by shaoshuai0102** [comment]
`+ cluster-client@1.3.1`

**Pull request merged**
